server:
  port: 9688
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.9.131.234:3306/xdu_help?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: username
    password: passwd
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

      #监控SpringBean
      aop-patterns: com.qzx.secondhand.*
      # 底层开启功能，stat（sql监控），wall（防火墙）
      filters: stat,wall,slf4j
      # 配置监控页功能
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: mysql
        reset-enable: false
      # 监控web需要开启
      web-stat-filter:
        enabled: true
      # filter的配置
      filter:
        # 对上面filters里面的stat的详细配置（sql监控配置）
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 30000
        # 防火墙配置 对某些sql语句进行拦截
        wall:
          enabled: true
          config:
            drop-table-allow: false
        slf4j:
          enabled: true

mybatis:
  mapper-locations: classpath:mapperXML/*.xml
  configuration:
    #带有下划线的表字段映射为驼峰格式的实体类属性
    map-underscore-to-camel-case: true

thread:
  pool:
    corePoolSize: 10
    maxPoolSize: 20
    keepAliveSeconds: 300
    queueCapacity: 40

user:
  token:
    # 7*24*60*60*1000 测试环境超时时间：一周
    expireTime: 604800000
